# Generated by Django 3.0.4 on 2020-03-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('arrival_time', models.DateTimeField(editable=False)),
                ('departure_time', models.DateTimeField()),
                ('is_late', models.BooleanField(default=False)),
                ('has_left_early', models.BooleanField(default=False)),
            ],
        ),
    ]
