# Generated by Django 3.0.4 on 2020-03-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveattendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='departure_time',
            field=models.DateTimeField(editable=False),
        ),
    ]
