# Generated by Django 3.0.4 on 2020-04-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveattendance', '0002_defaultersdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultersdata',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
    ]
