# Generated by Django 3.0.4 on 2020-03-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveattendance', '0002_auto_20200324_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='arrival_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
