# Generated by Django 3.0.4 on 2020-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveattendance', '0003_auto_20200407_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultersdata',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='defaultersdata',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
